In [94]:
import sklearn
import pywt
import numpy
import os
import pandas
from PIL import Image
from sklearn.model_selection import train_test_split

In [38]:
def haar_wavelet(img, counter = 3):
    if (counter == 0):
        return img.flatten()
    LL, (LH_, HL_, HH_) = pywt.dwt2(img, 'haar') # LL corresponds to the top left quad of the picture 
    return haar_wavelet(LL, counter - 1)

In [87]:
images_folder = "../CK+48/"

column_names = [i for i in range(0,36)]
image_coeffs = []
emotions = []

for dirname, dirs, files in os.walk(images_folder):
    for filename in files:
        image_to_read = numpy.asarray(Image.open("../CK+48/" + dirname + "/" + filename))
        coeffs = haar_wavelet(image_to_read)
        image_coeffs.append(coeffs)
        emotions.append(dirname.rsplit("/",1)[-1])

image_coeffs = numpy.array(image_coeffs)
print(image_coeffs)
images_df = pandas.DataFrame(image_coeffs, columns=column_names)
images_df["emotion"] = emotions


[[ 113.625  209.875 1028.5   ...  417.375  492.75  1014.375]
 [ 109.     215.    1034.375 ...  438.75   492.875  945.5  ]
 [ 104.625  186.25  1005.75  ...  397.625  475.625 1014.625]
 ...
 [  47.     514.    1692.875 ...  774.875 1371.5    582.5  ]
 [  41.     628.625 1755.125 ...  670.25  1437.375  585.125]
 [  42.625  584.875 1729.125 ...  692.375 1427.875  577.125]]


In [97]:
features = images_df.loc[:, column_names]
outcome = images_df.emotion

x_train, x_test, y_train, y_test = train_test_split(features, outcome, test_size=0.3,random_state=109) # 70% training and 30% test


          0         1         2         3         4        5        6   \
835  160.625   346.750   421.750   704.875   214.875  316.375  128.250   
396  202.500  1223.250  1887.125  1727.875  1341.375  515.250  201.375   
91   342.500  1353.500  1946.625  1987.625  1557.250  577.000  428.375   
633  193.375   837.750  1421.375  1460.625   822.000  107.750  226.500   
653  846.250  1142.500  1469.375  1431.375  1040.375  832.750  508.250   
..       ...       ...       ...       ...       ...      ...      ...   
399  488.750  1520.625  1867.000  1637.875   851.875  566.500  425.000   
141  387.875   402.250   649.500  1098.500   494.250  539.750  557.375   
757  658.500   978.000  2024.375  1999.000  1059.500  686.875  518.250   
245   57.625  1074.375  1668.125  1324.875   307.375   50.125  301.500   
262   52.500   426.000   468.375   793.250   278.875  110.875  182.875   

           7         8         9   ...        26        27        28  \
835   658.250  1092.250  1186.625  ... 